### ISSUE TITLE
createCenter sideLogic 

### ISSUE THREAD

**Issue by deannreid** [dayzai/DZAI#13]
An error with createcenter in DZAI_startup.sqf  line 54,

You defined a String and it needs a side :+1: 

http://gyazo.com/540c842516977b9e855da8dea8f1463b

**Comment by dayzai** [comment]
Line 54 does have sideLogic defined as a "side" and not a string: https://github.com/dayzai/DZAI/blob/master/DZAI/scripts/DZAI_startup.sqf

I'm thinking it's something on your server that's redefining sideLogic into a string using something like this:

sideLogic = "String";

Possibly the action of an antihack of some sort? Try replacing sideLogic with Civilian and see if that changes anything.

**Comment by dayzai** [comment]
Actually, try using the new modified DZAI_startup.sqf. I used a blank trigger object instead of a gamelogic unit, see if that helps anything.

https://github.com/dayzai/DZAI/commit/faf1b09ff5cee0e8a1b27dbf59746acb0a5f436a

**Comment by deannreid** [comment]
I use infiSTAR and my own anti-hack, mine doesn't define side logics so must be infiSTAR's if thats the cause, I'll update you on that script update :+1:

**Comment by deannreid** [comment]
It gets rid of the errors, but I'll let you know if there's any problems in-game

**Comment by deannreid** [comment]
Doesn't appear to be in-game problems either :+1:

**Comment by dayzai** [comment]
Thank you for the feedback. Since issue seems solved I'll be closing this issue.
